name: "Coding Standards"

on:
  push:

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-22.04"

    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: "cs2pr"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"

      # https://github.com/doctrine/.github/issues/3
      - name: "Run PHP_CodeSniffer"
        run: |
          vendor/bin/phpcs -q --no-colors --report=diff || true
          vendor/bin/phpcs -q --no-colors --report=checkstyle | cs2pr
