name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "mvorisek/.github/.github/workflows/coding-standards.yml@output-cs-diff"
